services:
  battery-api:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/v3/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
