services:
  ollama:
    image: ollama/ollama
    container_name: webai-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-network

volumes:
  ollama:

networks:
  ai-network:
    external: true
